### ISSUE TITLE
CRITICAL:  Duplicated code in car and trucks

### ISSUE THREAD

**Issue by I-Hansson** [hildalange/TDA553-lab1#19]
Metoderna gas(), brake(), incrementalSpeed(), decrementSpeed() finns i båda subklass hierarkierna. gas och break är även annorlunda implementerade för trucks. 

Då alla Vehicle ska kunna gasa och bromsa med implementation (baserad på speedfactor)  så kan man flytta upp de fyra metoderna i Vehicle klassen, då ärver alla cars och trucks implementationen ifrån vehicle.  (gas ska ta in ett värde mellan [0,1] och sedan kalla på incrementSpeed/decrementSpeed som i sin tur ändar currentSpeed) Ni har gjort en annan implementation i scania och CarTransporter just nu. 

Eftersom Scania och CarTransporter enbart kan åka vid ett speciellt villkor så kan vi Overridea metoden gas()(och brake()) i Truck: tex

    @Override
    public void gas(double amount) {
        if(  " kan vi åka?" ){
         super.gas(amount);
        }
    }
 Där "kan vå åka?"  är två olika vilkor som tex:   if ( currentAngle == 0 ) och if ( flatbedIsUP ) 

Super.gas() kallar på den allmäna metoden i vehicle som gör så att currentSpeed ökar.

Detta gör så att vi inte behöver skria samma kod flera gånger och att metoden som är privata kan bli privata som tex setCurrentspeed().

**Comment by I-Hansson** [comment]
Vi har fortfarande inte fått tillräckligt med kodduplicering, genom att flytta gas(), brake(), incrementalSpeed(), decrementSpeed() till Vehicle så kan vi använda dem som vanligt i car(saab/volvo) men i scania och carTransporter kan vi också använda dem genom att kalla på gas som i exemplet jag skrev ovan. 
Så: 
   @Override
    public void gas(double amount){
        if (platformAngle > 0){
            "gör inget eller kasta ett felmeddelande"
        } else {
            super.gas(amount);
    }
Så som det är implementerat just nu (i er kod) så kan vi kalla på gas och brake med vilken amount som helst. Detta vill vi inte då vi bart skall kunna kalla på gas och brake med en amount mellan 0<amount<1.

**Comment by I-Hansson** [comment]
Det är även bra att ha kvar subklassen Truck då det främjar OCP om vi skulle vilja lägga till fler "lastbilar". Där skulle även gemensam kod för gas och brake kunna ligga om ni använde er av delegation med platformen.

**Comment by johannaavlund** [comment]
Om vi inför truck som en subklass till vehicle där gemensam kod för gas och brake implementeras. Kan man göra en ny class där vi använder oss utav delegation för platformen som både Cartransporter och Scania använder (implementeras i båda classerna), eller ska den delegationen också implementeras i Truck?

**Comment by I-Hansson** [comment]
Ja det går jättebra att göra så. För att göra det så bra som möjligt så har scania och carTrasnporter två olika implementationer av hur man höjer/sänker och veta om bilen får köra. 
Det man skulle kunna göra är ett interface där de mest abstrakta och uppenbara metoderna finns, som tex lock /unlock **eller** raise/lower/canMove.

Efter detta så skapar vi två klasser en för scanias platform och en för carTrasnporters platform (båda classerna implementerar interfacet vi har skapat).
Dessa två klasser deligerar vi till ifrån scania och carTrasnsporter. 
Så scania har en scania platform:


public class Scania extends Truck(

IPlatform scaniaPlatform;

public Scania(){
       super(...)
       scaniaPlatform = new AnglePlatform();
}

public void raisePlatform(int angle)  {
        if( currentSpeed == 0){
        scaniaPlatform.raise(angle);
     }
}
.
.
.
mer metoder...
}
