### ISSUE TITLE
CRITICAL: CarTransporter can move while ramp is down

### ISSUE THREAD

**Issue by I-Hansson** [hildalange/TDA553-lab1#24]
https://github.com/hildalange/TDA553-lab1/blob/26c689de42d66d4b9bb8025bae028602ff7d456a/src/java/CarTransporter.java#L78-L86

**Comment by hildalange** [comment]
Vi förstår inte riktigt. Vi har ändrat och dubbelkollat, och i våra tester så rör sig inte bilen. Vad ska vi ändra?

**Comment by I-Hansson** [comment]
Enligt labben så skall carTransporten vara stilla när flatbed är nere och enbart kunna köra när flatbeden är uppe. 

Er variabel flatbedUp implicerar att när den är True så är platformen uppe och när den är False så är rampen nere. 
Nu när ni la till en metoderna för att höja och sänka kan inte röra sig.
