### ISSUE TITLE
CRITICAL: Can load more than maximum capacity of cars [Lab2]

### ISSUE THREAD

**Issue by I-Hansson** [hildalange/TDA553-lab1#27]
Ni har satt max  capacity till två men när listan är public kan man lägga till  oändligt många bilar i listan. 

https://github.com/hildalange/TDA553-lab1/blob/26c689de42d66d4b9bb8025bae028602ff7d456a/src/java/CarTransporter.java#L7

**Comment by I-Hansson** [comment]
Vi kan fortfarande lägga till hur många bilar som helst i listan med bilar då vi kan kalla på denna gettern genom att skriva:

transporter.getList().add("en bil")

https://github.com/hildalange/TDA553-lab1/blob/71d5489e3870f5300ba2956a33a825ef995dff14/src/java/CarTransporter.java#L27-L29

Ni använder: this.getList().size() på rad 43. så istället för att returnera hela listan skulle vi kunna ha en metod som istället returnerar antalet bilar i listan. 
public int getNumberOfCars() {
        return content.getList().size();
    }

**Comment by johannaavlund** [comment]
Detta är ändrat nu i klass Cartransporter, men är det okej att ha i content klassen:
   
 public ArrayList<Car> getList(){
        return listOfLoadedCars;
    }

eller kan man fortfarande ladda bilen med fler bilar än max? vårat test säger att man inte kan det

**Comment by I-Hansson** [comment]
Ja det är okej så länge som instans variabeln **Contents content** i carTransporter är privat.

**Comment by I-Hansson** [comment]
Ta bort denna metoden eller använd er av defensive copying.
https://github.com/hildalange/TDA553-lab1/blob/3b22b0982efebe50e3ff6343651e5d3ca1da786d/src/java/CarTransporter.java#L19-L21. 

Samma gäller denna metod: 

https://github.com/hildalange/TDA553-lab1/blob/3b22b0982efebe50e3ff6343651e5d3ca1da786d/src/java/RepairShop.java#L24-L26

**Comment by johannaavlund** [comment]
Har försökt mig på defensive copying, och lagt till:
   
 @Override
    public CarTransporter clone() {
        CarTransporter clonedCarTransporter = null;
        try {
            clonedCarTransporter = (CarTransporter) super.clone();
        } catch (CloneNotSupportedException e) {
            e.printStackTrace();
        }

i Cartransporter.

Men undrar hur jag kopplar detta och skickar in det ''klonade'' objektet till Contents för att skapa en ''klonad'' lista?

**Comment by johannaavlund** [comment]
Så, nu har jag pushat in en ny version där jag använt mig av defensive copy i Contents. Så när CT kallar på listan så får den en kopia av listan. Är detta ok?

**Comment by I-Hansson** [comment]
Ja det ser bra ut. Bra jobbat, nu är ni godkända på lab 2.
